//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication_3.ZipServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZipCodeModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ZipCodeModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZIPCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbbreviationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ZIPCode {
            get {
                return this.ZIPCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZIPCodeField, value) != true)) {
                    this.ZIPCodeField = value;
                    this.RaisePropertyChanged("ZIPCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Abbreviation {
            get {
                return this.AbbreviationField;
            }
            set {
                if ((object.ReferenceEquals(this.AbbreviationField, value) != true)) {
                    this.AbbreviationField = value;
                    this.RaisePropertyChanged("Abbreviation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZipServiceRef.IZipService")]
    public interface IZipService {
        
        // CODEGEN: Generating message contract since element name zip from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZipService/GetZipInfo", ReplyAction="*")]
        ClientApplication_3.ZipServiceRef.GetZipInfoResponse GetZipInfo(ClientApplication_3.ZipServiceRef.GetZipInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZipInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZipInfo", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication_3.ZipServiceRef.GetZipInfoRequestBody Body;
        
        public GetZipInfoRequest() {
        }
        
        public GetZipInfoRequest(ClientApplication_3.ZipServiceRef.GetZipInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetZipInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string zip;
        
        public GetZipInfoRequestBody() {
        }
        
        public GetZipInfoRequestBody(string zip) {
            this.zip = zip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZipInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZipInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication_3.ZipServiceRef.GetZipInfoResponseBody Body;
        
        public GetZipInfoResponse() {
        }
        
        public GetZipInfoResponse(ClientApplication_3.ZipServiceRef.GetZipInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetZipInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientApplication_3.ZipServiceRef.ZipCodeModel GetZipInfoResult;
        
        public GetZipInfoResponseBody() {
        }
        
        public GetZipInfoResponseBody(ClientApplication_3.ZipServiceRef.ZipCodeModel GetZipInfoResult) {
            this.GetZipInfoResult = GetZipInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZipServiceChannel : ClientApplication_3.ZipServiceRef.IZipService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZipServiceClient : System.ServiceModel.ClientBase<ClientApplication_3.ZipServiceRef.IZipService>, ClientApplication_3.ZipServiceRef.IZipService {
        
        public ZipServiceClient() {
        }
        
        public ZipServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZipServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZipServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZipServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication_3.ZipServiceRef.GetZipInfoResponse ClientApplication_3.ZipServiceRef.IZipService.GetZipInfo(ClientApplication_3.ZipServiceRef.GetZipInfoRequest request) {
            return base.Channel.GetZipInfo(request);
        }
        
        public ClientApplication_3.ZipServiceRef.ZipCodeModel GetZipInfo(string zip) {
            ClientApplication_3.ZipServiceRef.GetZipInfoRequest inValue = new ClientApplication_3.ZipServiceRef.GetZipInfoRequest();
            inValue.Body = new ClientApplication_3.ZipServiceRef.GetZipInfoRequestBody();
            inValue.Body.zip = zip;
            ClientApplication_3.ZipServiceRef.GetZipInfoResponse retVal = ((ClientApplication_3.ZipServiceRef.IZipService)(this)).GetZipInfo(inValue);
            return retVal.Body.GetZipInfoResult;
        }
    }
}
