//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZipServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZipCodeModel", Namespace="http://tempuri.org/")]
    public partial class ZipCodeModel : object
    {
        
        private string ZIPCodeField;
        
        private string CityField;
        
        private string StateField;
        
        private string AbbreviationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ZIPCode
        {
            get
            {
                return this.ZIPCodeField;
            }
            set
            {
                this.ZIPCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Abbreviation
        {
            get
            {
                return this.AbbreviationField;
            }
            set
            {
                this.AbbreviationField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZipServiceReference.IZipService")]
    public interface IZipService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZipService/GetZipInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<ZipServiceReference.GetZipInfoResponse> GetZipInfoAsync(ZipServiceReference.GetZipInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZipInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZipInfo", Namespace="http://tempuri.org/", Order=0)]
        public ZipServiceReference.GetZipInfoRequestBody Body;
        
        public GetZipInfoRequest()
        {
        }
        
        public GetZipInfoRequest(ZipServiceReference.GetZipInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetZipInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string zip;
        
        public GetZipInfoRequestBody()
        {
        }
        
        public GetZipInfoRequestBody(string zip)
        {
            this.zip = zip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZipInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZipInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZipServiceReference.GetZipInfoResponseBody Body;
        
        public GetZipInfoResponse()
        {
        }
        
        public GetZipInfoResponse(ZipServiceReference.GetZipInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetZipInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ZipServiceReference.ZipCodeModel GetZipInfoResult;
        
        public GetZipInfoResponseBody()
        {
        }
        
        public GetZipInfoResponseBody(ZipServiceReference.ZipCodeModel GetZipInfoResult)
        {
            this.GetZipInfoResult = GetZipInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IZipServiceChannel : ZipServiceReference.IZipService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class ZipServiceClient : System.ServiceModel.ClientBase<ZipServiceReference.IZipService>, ZipServiceReference.IZipService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ZipServiceClient() : 
                base(ZipServiceClient.GetDefaultBinding(), ZipServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IZipService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZipServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ZipServiceClient.GetBindingForEndpoint(endpointConfiguration), ZipServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZipServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ZipServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZipServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ZipServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZipServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZipServiceReference.GetZipInfoResponse> ZipServiceReference.IZipService.GetZipInfoAsync(ZipServiceReference.GetZipInfoRequest request)
        {
            return base.Channel.GetZipInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZipServiceReference.GetZipInfoResponse> GetZipInfoAsync(string zip)
        {
            ZipServiceReference.GetZipInfoRequest inValue = new ZipServiceReference.GetZipInfoRequest();
            inValue.Body = new ZipServiceReference.GetZipInfoRequestBody();
            inValue.Body.zip = zip;
            return ((ZipServiceReference.IZipService)(this)).GetZipInfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IZipService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IZipService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/ZipServiceRepXMLSerializer/ZipService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ZipServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IZipService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ZipServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IZipService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IZipService,
        }
    }
}
